---
resource_types:
  - name: helm
    type: docker-image
    source:
      repository: linkyard/concourse-helm-resource
  - name: kube-authenticator
    type: docker-image
    source:
      repository: 7imbrook/kube_authenticate

resources:
  - name: podcast
    type: git
    icon: github-circle
    source:
      uri: "https://github.com/timbrook-life/podcast"
      branch: master
      ignore_paths:
        - values.yaml
        - ci/*
  - name: podcast-deploy
    type: git
    icon: github-circle
    source:
      uri: "https://github.com/timbrook-life/podcast"
      branch: master
      paths:
        - values.yaml
  - name: podcast-binary
    type: docker-image
    source:
      username: ((docker.username))
      password: ((docker.password))
      repository: 7imbrook/podcast
  - name: auth
    type: kube-authenticator
    icon: lock-outline
    source:
      token: ((digital_ocean.token))
  - name: helm-release
    type: helm
    source:
      repos:
        - name: personal
          url: https://helm-charts.sfo2.digitaloceanspaces.com
jobs:
  - name: Build
    serial: true
    plan:
      - get: podcast
        trigger: true
      - put: podcast-binary
        params:
          build: podcast
        get_params: { skip_download: true }
        inputs:
          - podcast
  - name: Binary Push
    serial: true
    plan:
      - get: podcast-binary
        params:
          skip_download: true
        trigger: true
        passed:
          - Build
      - get: auth
      - get: podcast-deploy
        trigger: true
      - put: helm-release
        params:
          release: podcast
          namespace: production
          kubeconfig_path: auth/config.yaml
          chart: personal/appshell
          version: 1.0.17
          values: podcast-deploy/values.yaml
          show_diff: true
          override_values:
            - key: image.sha
              path: podcast-binary/digest
              type: string
