---
resource_types:
  - name: helm
    type: docker-image
    source:
      repository: linkyard/concourse-helm-resource
  - name: kube-authenticator
    type: docker-image
    source:
      repository: 7imbrook/kube_authenticate

resources:
  - name: podcast
    type: git
    icon: github-circle
    source:
      uri: "https://github.com/timbrook-life/podcast"
      branch: master
  - name: podcast-binary
    type: docker-image
    source:
      username: ((docker.username))
      password: ((docker.password))
      repository: 7imbrook/podcast
  # - name: auth
  #   type: kube-authenticator
  #   icon: lock-outline
  #   source:
  #     token: ((digital_ocean.token))
  # - name: helm-release
  #   type: helm
  #   source:
  #     repos:
  #       - name: personal
  #         url: https://helm-charts.sfo2.digitaloceanspaces.com
jobs:
  - name: Build
    serial: true
    plan:
      - get: podcast
        trigger: true
      - put: podcast-binary
        params:
          build: podcast
        inputs:
          - podcast
